### ISSUE TITLE
REQUIRED FEATURE: Logging facility needed

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#1]
Loggable actions:
--user cancels/confirms order
--admin adds/removes product

**Comment by elfiesmelfie** [comment]
Log can be maintained in a file or in a database.
Which one do we want?

**Comment by daradermody** [comment]
I'd recommend using a file; easier to access.

**Comment by elfiesmelfie** [comment]
In that case, can you or Patrick do it? Just append to a file when a
certain action is carried out.

**Comment by Lexoph** [comment]
I will implement the logging function as well. It won't take long, I hope.
