### ISSUE TITLE
Admin: remove product

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#10]
Required admin action

**Comment by elfiesmelfie** [comment]
The interactProduct EJB provides this functonality... 
- removeProduct(int id): void

**Comment by elfiesmelfie** [comment]
Assigned to Dara for servlet/front-end implementation

A check is needed to make sure the user is an admin

**Comment by Lexoph** [comment]
This is done by simply clicking on the remove button when the admin is viewing the product's page.
