### ISSUE TITLE
Admin: increase/decrease product quantity

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#11]
required admin action

**Comment by elfiesmelfie** [comment]
interactProduct EJB
- updateQuantity(int pid, int diff): boolean

use positive (for purchases) or negative values (for adding extra stock)

**Comment by daradermody** [comment]
I understand that it refers to 'positive' purchases, but is it not counter-intuitive to have positive values a negation of quantity?

**Comment by elfiesmelfie** [comment]
Whatever number you put in will be deducted from the quantity...
**THERE IS A NAMED QUERY WITH THAT DEDUCTION.**

**Comment by daradermody** [comment]
I understand that. But as general 'update quantity' function, is it not more intuitive to 'deduct' with a 'minus' when a purchase is made, and 'add' with a 'positive' when more products come in?

**Comment by elfiesmelfie** [comment]
That would require two almost identical methods!

**Comment by elfiesmelfie** [comment]
You can now call **interactionBeans.interactProduct.increaseQuantity(pid, amount)**, and **interactionBeans.interactProduct.reduceQuantity(pid, amount)** with positive integers in each case.
I'm fed up with all this stuff, I hope I'm nearly done :'( I'm not in the right frame of mind to go any deeper with the changes.

**Comment by Lexoph** [comment]
Thanks, Emma! I called both of these methods.
