### ISSUE TITLE
Current Requests

### ISSUE THREAD

**Issue by Lexoph** [daradermody/DistSysProj3#14]
addProduct.jsp
-> Call to add product to list, return boolean if successfully added
    -> Must be able to simply access the product attributes as in:
        ~~Product newProd = new Product()~~
        ~~newProd.~~ String Title = productTitle.textArea.selectText() <----This selectText will be clarified later on
        ...
        ~~ProductList.add(newProd)~~
     **You can get all the parameters, and then call interactProduct.addProduct(...) and this will add a new product to the DB. No bool returned, but there will be an error if it is unsuccessful.**
-> Will forward to browse page

index.jsp
-> Call to return an ArrayList of All Products (Product Data Type)
**interactProduct.findAllProducts(): List<Product>**

-> Call to return an ArrayList of Products in Shopping Cart -> Will simply access ID's User's Shopping Cart
*_See interactionBeans.interactCustomer, and then (war) User for a modified User class that can be used with the former Security class. *_

-> Call to add product to shopping cart, return true if successful
    -> User.ShoppingCart.add((String)itemID)
        -> Refresh page with item now in shopping cart, only if returned true
-> Call to decrease amount of Product and return back the amount of Product
    -> if(itemID.Product.decreaseAmount() == 0)
        -> Call to remove the list in ProductList
            -> ProductList.remove(itemID)
            -> Don't worry about retaining the product attributes for each amount increase for later, just delete.
         **There is a built-in check in interactProduct.updateQuantity()**
    -> Will only allow the purchase of item 1 at a time for now

browseProduct.jsp
-> Call to change amount of Product, return the amount of item:
    -> Item(with corresponding Item ID).amount = itemAmount.selectText()
            **Using a DB... stuff needs to persist... interactProduct.increaseQuantity(pid, quantity): boolean **
            **You cannot change the absolute amount of a product, just the relative amount (eg +10, or -2, etc)**
        -> Refresh back to item page again
-> Must be able to access the item attributes:
       -> itemID.Product.xxxxx
       **prod.getXXX or, if necessary: interactProduct.searchByID(pid).getXXX**
-> Call to return product comments, return an array list of comments
       ->itemID.Comments
       **interactProduct.getComments(pid): List<Comment>**
-> Display comments similar to how we displayed messages in the forum threads

checkout.jsp
-> Simply a confirmation saying, 'Thank you for choosing Koalascense.\nWe wish you the best of luck in your adventures.
                \nTry and catch 'em all!'
-> Sleep in this page for around 15 seconds and forward to browse items (index) page.
-> Clear shopping cart
    -> ID.User.shoppingCart.clear()

shoppingCart.jsp
-> Must list the trolley items, similar to index.jsp page
        **shoppingCart.getItems(): List<Product>**

header.jsp
-> Add site logo
-> Improve search bar
    -> Search button
        -> Call to search EACH of the databases, input parameter of keyword, and return an 
            ArrayList of Products  

searchResults.jsp
-> Each of the search results (items) must be added as a list, similar to the index.jsp list of items

login.jsp
-> Use what we have now but create another cookie to store privilege level

errorPage.jsp
-> Don't touch for now

ALL pages
-> Checks for authorisation and must also have a cookie or something similar to check the ID's associated privilege level

I need the stickied shopping cart list.

Aesthetics will be done later on.

**Comment by elfiesmelfie** [comment]
Who exactly will be doing all this? I'm confused...

**Comment by Lexoph** [comment]
This is more of a placeholder for what needs to be done for the front-end. I don't remember which of you (Dara & Emma) has to do what so just sift through the list to see which may apply to you.
Just focus more on the 'Call to return XXX' items.

**Comment by elfiesmelfie** [comment]
Can you remove anything that has been covered in a previous issue? Or
create single tasks? It's really much easier to deal with smaller bits of
info.

**Comment by Lexoph** [comment]
It's better for me to read this in one document rather than having to keep track of all the little bits. This is more for my sanity.

**Comment by elfiesmelfie** [comment]
Can you match up your requests with other Issues, and keep track of the method calls here?
There are a number of items that have already been fulfilled, and tagged as "Frontend".
