### ISSUE TITLE
Are we using Security class? Or are we usign a simple login using cookies?

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#15]
The brief stated that there was no need for the session stuff, and it might not work very well cos I'm terrible at integration.

**Comment by daradermody** [comment]
Since we already have it created and the whole hierarchy of routine calls for verification and sanitisation from the previous project is carried over, I think we should keep using it.

**Comment by elfiesmelfie** [comment]
There are one or two problems with the integration though, so someone front end needs to assess that. EJBs can't be called from a static context...

**Comment by elfiesmelfie** [comment]
Is this actually working correctly yet?

**Comment by elfiesmelfie** [comment]
Question is actually resolved, we ARE using Security class, but it might have been better as an EJB.
