### ISSUE TITLE
Where are the images stored in a project such as this?

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#16]
I'm trying to figure out where to put the images for products, and how to refer to them... Absolute address won't work, but what kind of relative addressing?

**Comment by daradermody** [comment]
For displaying images on the front-end, the JSP pages use the images/ folder; what is it that you want saving images (an object, etc.)?

**Comment by elfiesmelfie** [comment]
Huh?  I'm storing the image paths as strings in a db. Front end accesses them, and uses them add the sources in an img tag. Give me a sample path for an image in the images folder,  and I'll get the correct format for the image paths.

**Comment by daradermody** [comment]
An example of a string path the frond-end code would need would be: "images/login-image.png". If this path is only used (to find the image) by the JSP pages, then a relative path, with the "images" folder in the same location as the JSP pages (which is already the case), is sufficient.

**Comment by elfiesmelfie** [comment]
I have added the images, and their addresses.
