### ISSUE TITLE
Password hashes needed

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#2]
The following passwords are required, and since we're using the same scheme as before, I need password hashes to put in the database.
     user: joe ------- pwd: "1tbh?5g"
     admin: toor --- pwd: "4u!ido@"

**Comment by daradermody** [comment]
Hash of 1tbh?5g: "6a596ae6054d3abd355a9d7d59ac3b60ed6a6aa8"
Hash of 4u!ido@: "de755721ab257ae56c9bd0aa1566e109dec80216"

**Comment by elfiesmelfie** [comment]
Not the hashes I needed....
Are we using the same scheme as before?
The hashes should be longer...

**Comment by elfiesmelfie** [comment]
Sorry, the hashes were really short in the email, sorry for that.... They only appeared as about 8-characters cos github mistook them for commit hashes
