### ISSUE TITLE
search product by name

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#5]
required user action

Front-end: Display all results

**Comment by elfiesmelfie** [comment]
Need back-end support first.... I'll just implement that...

**Comment by elfiesmelfie** [comment]
interactProduct EJB
- searchProductByKeyword(String kw):  List<Product>

To search for multiple keywords, call this function multiple times. or else you'll get no results, unless the description/summary/title matches the exact phrase.

**Comment by Lexoph** [comment]
Done, along with the other one!
