### ISSUE TITLE
Add displayed item to cart

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#6]
Required user action

**Comment by elfiesmelfie** [comment]
Dara or Niko... I don't think this has anything to do with me?? 
Unless you want a shopping cart (non-persistent) data type

**Comment by elfiesmelfie** [comment]
So far:
shoppingCartBean.add(Product ): void

**Comment by elfiesmelfie** [comment]
Dara/Patrick, how can I use a shoppingCartBean that is stateful and associate it with a customer for the duration of the session?
Will I need a shoppingCartBean attribute in the Customer class? Injection?

**Comment by daradermody** [comment]
Are you sure that is the proper use of a bean? And also, should these beans not be stateless?

**Comment by elfiesmelfie** [comment]
The shopping cart bean is stateful...
I've used some of Reiner's code from the EJB example, I'm still having trouble with the checkout logic though.

**Comment by Lexoph** [comment]
I'm doing all the checkout logic. I was able to use your methods properly to implement this. Testing needs to be done but it looks satisfactory so far.
