### ISSUE TITLE
add comments to any product

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#7]
Required user Action

**Comment by elfiesmelfie** [comment]
Front end stuff, this is general functionality. I have some named queries for getting the comments and adding comments, it involves using the product id.

**Comment by elfiesmelfie** [comment]
interactProduct EJB
- addComment(Product p, Customer c, String content): void

**Comment by Lexoph** [comment]
Similar mechanism to the forum messages.
