### ISSUE TITLE
Admin: add new product

### ISSUE THREAD

**Issue by elfiesmelfie** [daradermody/DistSysProj3#9]
required admin action

**Comment by elfiesmelfie** [comment]
interactProduct EJB
+addProduct(String title, String description, int quantity, int price, String imagepath, String summary) : void

**Comment by Lexoph** [comment]
Separate page for adding a new product - the only aspect I wasn't able to properly check is the image file path one. This will need to be retested when the database is working as I don't think it will work properly. (For now, it's sufficient.)
